import { NextResponse } from 'next/server';
import { generateGreeting } from '@/lib/services/huawei-modelarts.service';

/**
 * Test endpoint to verify greeting generation
 * Visit: http://localhost:3000/api/test-greeting
 * 
 * Note: This will use fallback greetings if ModelArts is not configured
 */
export async function GET() {
  try {
    console.log('=== Testing Greeting Generation ===');
    
    const hasModelArts = !!process.env.HUAWEI_MODELARTS_ENDPOINT;
    console.log('ModelArts configured:', hasModelArts);
    
    const startTime = Date.now();
    const greeting = await generateGreeting({
      timeOfDay: 'morning',
    });
    const duration = Date.now() - startTime;
    
    console.log(`✓ Greeting generated in ${duration}ms`);
    console.log(`Greeting: "${greeting}"`);
    
    return NextResponse.json({
      success: true,
      message: hasModelArts 
        ? 'ModelArts greeting generation successful! ✓'
        : 'Using fallback greeting (ModelArts not configured)',
      greeting,
      modelArtsConfigured: hasModelArts,
      generationTime: `${duration}ms`,
      note: hasModelArts 
        ? 'This greeting was generated by your ModelArts model'
        : 'This is a predefined fallback greeting. Add HUAWEI_MODELARTS_ENDPOINT to use AI-generated greetings.',
      nextSteps: hasModelArts 
        ? ['ModelArts is working! ✓', 'Greetings will be AI-generated']
        : ['Fallback greetings are working', 'To use AI: Deploy a ModelArts model and add HUAWEI_MODELARTS_ENDPOINT']
    });
  } catch (error) {
    console.error('❌ Greeting generation failed:', error);
    
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    
    return NextResponse.json({
      success: false,
      error: errorMessage,
      possibleCauses: [
        'ModelArts endpoint incorrect or unreachable',
        'Model not deployed or not running',
        'IAM token authentication failed',
        'Network connectivity issues',
      ],
      note: 'ModelArts is OPTIONAL. The app will use fallback greetings if it fails.',
      troubleshooting: {
        step1: 'Verify model is deployed and running in ModelArts console',
        step2: 'Check HUAWEI_MODELARTS_ENDPOINT is correct',
        step3: 'If not using ModelArts, you can ignore this error - fallback greetings will be used',
      }
    }, { status: 500 });
  }
}

